### ISSUE TITLE
Multiple motion events (how to differentiate)

### ISSUE THREAD

**Issue by weitheng** [dermotduffy/hass-motioneye#91]
I am running the latest core version of the motioneye integration component. I am aware that the core version does not support binary sensors by default, but I am required to manually turn an event into a binary sensor. 

Just wondering, how to differentiate motion events from multiple cameras in motioneye since the event_type will be the same for the motion events, `event_type: "motioneye.motion_detected"`?

**Comment by dermotduffy** [comment]
Reviewing the event contents will help, see: https://github.com/dermotduffy/hass-motioneye#example-motion-detected-event

Any of these keys will differ per camera:

```
        "device_id": "662aa1c77653bbc4af836abcdfaaaaaa",
        "name": "Office",
        "camera_id": "2",
```

**Comment by weitheng** [comment]
So when adding the template, I should include in the configurations? This is probably a stupid question, but how do I include it in the trigger template?

```
template:
  trigger:
    platform: event
    event_type: "motioneye.motion_detected"
  binary_sensor:
    - name: Event recently fired
      auto_off: 5
      state: "true"
```

**Comment by dermotduffy** [comment]
Apologies, I don't have time to test this, but try something like this:

```yaml
template:
  trigger:
    platform: event
    event_type: "motioneye.motion_detected"
    event_data:
      name: "<your_camera_name>"
  binary_sensor:
    - name: Event recently fired
      auto_off: 5
      state: "true"
```

You could also use the `device_id` or `camera_id` instead of name, in the `event_data` field.
